

on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      # MacOS 전용으로 빌드 할 때에는 Java 셋업이 필요 없다.
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
      - run: flutter pub get
     # Run integration test
     - name: Run Flutter Integration tests
       uses: reactivecircus/android-emulator-runner@v2
       with:
         target: google_apis
         api-level: 29
         arch: x86_64
         profile: Nexus 6
         # 기본적으로 Emulator 하나만 실행되므로, -d 옵션이 필요 없지 않나?
         script: flutter test integration_test